server:
  port: 10010

spring:
  application:
    name: api-web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth-service/**
    search-service: /search-service/**
    #seller-service: /seller/**
ribbon:
  ConnectTimeout: 100
  ReadTimeout: 600
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
sc:
  jwt:
    pubKeyPath: E:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      - /regist
      - /sms
      - /login
      - /categorys
      - /news
      - /floors
      - /brands
      - /specifications
      - /esData
      - /search
      - /goods
      - /comments